### ISSUE TITLE
Remake of club homepage

### ISSUE THREAD

**Issue by Pavi143** [coding-club-gct/coding-club-gct#1]
I have made a remake of club homepage, link to the repository [here](https://github.com/Pavi143/homepage)
This adds two more features:
- Light and dark theme based on  [official theme](https://github.com/coding-club-gct/theme)
- Automate student signup to our discord server

**Comment by useEffects** [comment]
Thank you for your interest, you can transfer the repo to our org whenever you are up for it !

**Comment by Pavi143** [comment]
Done, you can also close the issue.
